### PR TITLE
really skip label check by ignoring incoming labels

### PR DESCRIPTION
**Pull request by replay**
currently the flag `SkipInboundLabelCheck` doesn't really make memberlist skip the label check, because if this flag is enabled and the memberlist client is configured with no label and then it receives a message that has a label then prints a warning and drops the received message. I think if `SkipInboundLabelCheck` is enabled then it shouldn't matter whether incoming messages have a label, at all.

### CODE REVIEW

**Comment by 56quarters** [comment]
Am I correct that this change is only required during the migration of a cluster that doesn't use to labels to start using them? If so should we plan to upstream this at all or just add it to our fork temporarily? I suppose this is useful for more than just Mimir so perhaps upstreaming makes sense.

**Comment by replay** [comment]
> Am I correct that this change is only required during the migration of a cluster that doesn't use to labels to start using them? 

Correct

> If so should we plan to upstream this at all or just add it to our fork temporarily? I suppose this is useful for more than just Mimir so perhaps upstreaming makes sense.

I think upstreaming it makes sense, because as you said it could be useful to more people. I want to test it first in a real-world scenario before upstreaming though

**Review by pr00se — APPROVED** [review]

**Comment by pracucci** [comment]
I checked the original PR https://github.com/hashicorp/memberlist/pull/246 to see if there was any discussion about `SkipInboundLabelCheck`, cause it looks weird the way it was implemented. I'm wondering if it's us missing something.

**Review by pracucci — APPROVED** [review]
I keep not understanding why it was implemented that way in the original PR, but after double checking the code I think this change is good.

**Comment by slim-bean** [comment]
>I keep not understanding why it was implemented that way in the original PR, but after double checking the code I think this change is good.

I also looked at the initial PR and I'm not sure why it was implemented the way it is, I suspect it was an oversight because the way it's implemented in main doesn't seem like it really serves any useful purpose:

If the flag is true: any packet with a label will fail
If the flag is false: any packet with a label will fail

¯\\\_(ツ)\_/¯

**Comment by pracucci** [comment]
4 people looking at it, and looks good, so let's merge it.

**Pull request merged**
